train:              data/
output_dir:         adapters/
save_checkpoints:   True
template:           chatml
max_length:         1024
learning_rate:      1.0e-7
epochs:             1
plot:               loss.png